# Generated by Django 5.2.7 on 2025-10-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
