# Generated by Django 5.2.7 on 2025-11-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('Airport Pickup & Drop', 'Airport Pickup & Drop'), ('Tirumala Temple Visit', 'Tirumala Temple Visit'), ('Outstation Trip', 'Outstation Trip'), ('City Ride', 'City Ride'), ('Custom / Other', 'Custom / Other')], max_length=40)),
                ('pickup', models.CharField(max_length=200)),
                ('drop', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
