# Generated by Django 5.2.7 on 2025-11-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
